### ISSUE TITLE
Support reloading configuration & mTLS certificates on SIGHUP

### ISSUE THREAD

**Issue by karimodm** [iotaledger/remote-signer#1]
Keys and certificates are subject to periodic rotation; since the Coo will rely hardly on this service, it will be nice to be able to swap certificates and keys without interrupting service to the Coordinator or severing active connections. A SIGHUP is usually the standard signal to react to.

In specific:

* Dispatcher should be able to reload the `signers` config section, learning about new pubkeys and their relative endpoints;
* Dispatcher's `tonic::transport::Server` can be left alone, since it is a plain HTTP endpoint;
* Dispatcher should be able to reload its `tlsauth` config section in order to build `SignerClient`s with new certificates;
* Signer should be able to reload its `keys` and `tls` section to get acquainted with new keys and server certificate. The `tonic::transport::Server` should be rebuilt and restarted to serve the new certificate, while not interrupting current active connections.

**Comment by GalRogozinski** [comment]
TLS authentication removed.
Will be taken care of by using proxies.
